server:
  port: 8890
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 1173389434xy
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy年MM月dd日 hh时mm分ss秒
    time-zone: GMT+8
logging:
  file:
    path: D:\天津师范大学\code\MyGitRepository\springBoot2023_03_02\log
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    自定义参数
config:
  pageSize: 8